server:
  error:
    include-binding-errors: always
    include-message: always

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  datasource:
    url: jdbc:mysql://sql.freedb.tech:3306/freedb_spring_demo
    username: freedb_spring_demo
    password: bcgTYJ2X!RuM&FV
    driver-class-name: com.mysql.cj.jdbc.Driver
